### ISSUE TITLE
license

### ISSUE THREAD

**Issue by xuwei-k** [Philippus/sbt-jackson-version-check#2]
MPL or Apache? 🤔 

https://github.com/Philippus/sbt-jackson-version-check/blob/2c4e5718cbd9ead555863cdce5e1731053eedc84/build.sbt#L5

https://github.com/Philippus/sbt-jackson-version-check/blob/2c4e5718cbd9ead555863cdce5e1731053eedc84/LICENSE#L2-L4

**Comment by Philippus** [comment]
Nice catch, should be Apache 2.0.
